backend:
  name: git-gateway
  branch: main
media_folder: "src/assets/images"
public_folder: "/assets/images"
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "src" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page.njk"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/nav.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: true
            label_singular: nav item
            collapsed: true
            fields:
              - label: Title
                name: title
                widget: string
              - label: URL
                name: url
              - label: Sub Nav
                name: subnav
                widget: list
                label_singular: nav item
                allow_add: true
                collapsed: false
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: URL
                    name: url
                    widget: string